"""Transaction model"""
from sqlalchemy import Column, Integer, String, TIMESTAMP, DECIMAL, text, TEXT
from database import Base

class DSITransactionLog(Base):
    __tablename__ = "dsitransactionlog"
    
    RecordID = Column(Integer, primary_key=True, autoincrement=True)
    RecordStatus = Column(String(1))
    ProcessMethod = Column(String(1))
    TransactionType = Column(String(1))
    ServerName = Column(String(63))
    DeviceID = Column(String(64))
    UserID = Column(String(64))
    DeviceLocalTime = Column(String(14))
    DeviceUTCTime = Column(String(14))
    DeviceSequenceID = Column(String(2))
    WhenReceived = Column(String(14))
    WhenProcessed = Column(String(14))
    WhenExtracted = Column(String(14))
    ElapsedTime = Column(DECIMAL(10, 0))
    AppID = Column(String(30))
    AppVersion = Column(String(10))
    AppItemID = Column(String(60))
    WorldHostID = Column(String(2))
    ConnectorID = Column(String(50))
    FunctionDefVersion = Column(Integer)
    FunctionCallID = Column(String(100))
    FunctionCallRC = Column(String(1))
    DataIn = Column(TEXT)
    DataOut = Column(TEXT)
    ErrorsOut = Column(TEXT)
    SecurityID = Column(String(255))
    GUID = Column(String(50), unique=True, nullable=False)
    UnitID = Column(String(10))
    PromotionLevelID = Column(String(10))
    EnvironmentID = Column(String(10))
    Marking = Column(String(3))
    OrgUnitID = Column(String(50))
    TrackingReference = Column(String(200))


class ArchiveDSITransactionLog(Base):
    __tablename__ = "dsitransactionlogarchive"
    
    RecordID = Column(Integer, primary_key=True, autoincrement=True)
    RecordStatus = Column(String(1))
    ProcessMethod = Column(String(1))
    TransactionType = Column(String(1))
    ServerName = Column(String(63))
    DeviceID = Column(String(64))
    UserID = Column(String(64))
    DeviceLocalTime = Column(String(14))
    DeviceUTCTime = Column(String(14))
    DeviceSequenceID = Column(String(2))
    WhenReceived = Column(String(14))
    WhenProcessed = Column(String(14))
    WhenExtracted = Column(String(14))
    ElapsedTime = Column(DECIMAL(10, 0))
    AppID = Column(String(30))
    AppVersion = Column(String(10))
    AppItemID = Column(String(60))
    WorldHostID = Column(String(2))
    ConnectorID = Column(String(50))
    FunctionDefVersion = Column(Integer)
    FunctionCallID = Column(String(100))
    FunctionCallRC = Column(String(1))
    DataIn = Column(TEXT)
    DataOut = Column(TEXT)
    ErrorsOut = Column(TEXT)
    SecurityID = Column(String(255))
    GUID = Column(String(50), unique=True, nullable=False)
    UnitID = Column(String(10))
    PromotionLevelID = Column(String(10))
    EnvironmentID = Column(String(10))
    Marking = Column(String(3))
    OrgUnitID = Column(String(50))
    TrackingReference = Column(String(200))